// Theme.zig
const std = @import("std");
const Vapor = @import("vapor");
const Color = Vapor.Types.Color;
pub const Mode = enum(u8) {
    light,
    dark,
};

pub const ThemeTokens = enum(u8) {
    none,
    border_color,
    text_color,
    background,
    primary,
    secondary,
    border_cache_color,
    btn_color,
    tint,
    dark_tint,
    text_tint_color,
    alternate_tint,
    btn_tint,
    dark_text,
    form_input_border_color,
    danger,
    alternate_background,
    alternate_border_color,
    alternate_text_color,
    logo,
    gradient_start_0stop_color,
    gradient_start_100stop_color,
    gradient_end_0stop_color,
    gradient_end_100stop_color,
    icon_color,
    image_bg,
    code_background,
    highlight_color,
    border_color_light,
    grid_color,
    code_text_color,
    code_function_color,
    code_keyword_color,
    disabled,
    light_text,
    code_tint_color,
    code_comment_color,
    code_string_color,
    code_type_color,
    code_component_color,
    code_operator_color,
    code_identifier_color,
    code_is_added_color,
    chart_bar_color,
    text_muted,
};

pub const Colors = struct {
    border_color: Color,
    text_color: Color,
    background: Color,
    primary: Color,
    secondary: Color,
    font_family: []const u8,
    btn_color: Color,
    tint: Color,
    dark_tint: Color,
    text_tint_color: Color,
    alternate_tint: Color,
    btn_tint: Color,
    dark_text: Color,
    form_input_border_color: Color,
    danger: Color,
    alternate_background: Color,
    alternate_border_color: Color,
    alternate_text_color: Color,
    logo: Color,
    gradient_start_0stop_color: Color,
    gradient_start_100stop_color: Color,
    gradient_end_0stop_color: Color,
    gradient_end_100stop_color: Color,
    icon_color: Color,
    image_bg: Color,
    code_background: Color,
    highlight_color: Color,
    border_color_light: Color,
    grid_color: Color,
    code_text_color: Color,
    code_function_color: Color,
    code_keyword_color: Color,
    disabled: Color,
    light_text: Color,
    code_tint_color: Color,
    code_comment_color: Color,
    code_string_color: Color,
    code_type_color: Color,
    code_component_color: Color,
    code_operator_color: Color,
    code_identifier_color: Color,
    code_is_added_color: Color,
    chart_bar_color: Color,
    text_muted: Color,
};

pub const Light = Colors{
    .border_color = .hex("#262626"),
    // .border_color_light = .hex("#C3C1C1"),
    .border_color_light = .hex("#e4e4e4"),

    .text_color = .rgba(0, 0, 0, 255),
    .background = .white,
    // .background = .hex("#F0F0F0"),
    .primary = .rgba(255, 255, 255, 255),
    .secondary = .rgba(0, 0, 0, 255),
    .font_family = "Montserrat",
    .btn_color = .hex("#2108FF"),
    .tint = .hex("#002bff"),
    // .tint = .hex("#C2FE0A"),
    .dark_tint = .hex("#020089"),
    .text_tint_color = .white,
    .alternate_tint = .hex("#2108FF"),
    .btn_tint = .hex("#FF3838"),
    .dark_text = .hex("#FDFDFD"),
    .form_input_border_color = .hex("#E9E9E9"),
    .danger = .rgba(255, 78, 51, 255),
    .alternate_background = .hex("#262626"),
    .alternate_border_color = .hex("#262626"),
    .alternate_text_color = .hex("#ffffff"),
    .logo = .hex("#ffffff"),
    .gradient_start_0stop_color = .hex("#4800FF"),
    .gradient_start_100stop_color = .hex("#7A38FF"),
    .gradient_end_0stop_color = .hex("#FFE09E"),
    .gradient_end_100stop_color = .hex("#FFFFFF"),
    .icon_color = .hex("#A2A2A2"),
    .image_bg = .hex("#ffffff"),
    .code_background = .white,
    .highlight_color = .hex("#F3F3F3"),
    .grid_color = .hex("#f6f6f6"),
    .code_text_color = .hex("#E4E7EE"),
    .code_function_color = .hex("#FFED84"),
    .code_keyword_color = .hex("#002bff"),
    .disabled = .hex("#A2A2A2"),
    .light_text = .hex("#B7B7B7"),
    .code_tint_color = .hex("#84FFED"),
    .code_comment_color = .hex("#767676"),
    .code_string_color = .hex("#C4A262"),
    .code_type_color = .hex("#7D7684"),
    .code_component_color = .hex("#FF00FF"),
    .code_operator_color = .hex("#565656"),
    .code_identifier_color = .hex("#2E3B5A"),
    .code_is_added_color = .hex("#16DF8F"),
    .chart_bar_color = .hex("#212121"),
    .text_muted = .hex("#71717a"),
};

pub const Dark = Colors{
    .border_color = .hex("#27272a"),
    .text_color = .hex("#EAEAEA"),
    .background = .hex("#0F0F0F"),
    .primary = .rgba(0, 0, 0, 255),
    .secondary = .rgba(255, 255, 255, 1),
    .font_family = "Montserrat",
    .btn_color = .hex("#FFFF15"),
    .tint = .hex("#C2FE0A"),
    .dark_tint = .hex("#D5E100"),
    .text_tint_color = .hex("#C2FE0A"),
    .alternate_tint = .hex("#6338FF"),
    .btn_tint = .hex("#FF3838"),
    .dark_text = .hex("#0B0B0B"),
    .form_input_border_color = .hex("#27272a"),
    .danger = .rgba(255, 78, 51, 1),
    .alternate_background = .hex("#262626"),
    .alternate_border_color = .white,
    .alternate_text_color = .hex("#0F0F0F"),
    .logo = .hex("#0F0F0F"),
    .gradient_start_0stop_color = .hex("#EEFF00"),
    .gradient_start_100stop_color = .hex("#ccff00"),
    .gradient_end_0stop_color = .hex("#FFFFFF"),
    .gradient_end_100stop_color = .hex("#ffffff"),
    .icon_color = .hex("#484848"),
    .image_bg = .hex("#0F0F0F"),
    .code_background = .hex("#181818"),
    .highlight_color = .hex("#27272a"),
    .border_color_light = .hex("#1E1E1E"),
    .grid_color = .hex("#1E1E1E"),
    .code_text_color = .hex("#F6F5FB"),
    .code_function_color = .hex("#b392f0"),
    .code_keyword_color = .hex("#F97583"),
    .code_tint_color = .hex("#4da5ff"),
    .disabled = .hex("#32333a"),
    .light_text = .hex("#2108FF"),
    .code_comment_color = .hex("#6A6A6A"),
    .code_string_color = .hex("#9F9C46"),
    .code_type_color = .hex("#817E9F"),
    .code_component_color = .hex("#B5EF8A"),
    .code_operator_color = .hex("#424242"),
    .code_identifier_color = .hex("#525C73"),
    .code_is_added_color = .hex("#085436"),
    .chart_bar_color = .hex("#272727"),
    .text_muted = .hex("#71717a"),
};

pub var mode: Mode = .light;

pub export fn setTheme(new_mode: Mode) void {
    mode = new_mode;
    std.log.info("Theme set to {s}", .{@tagName(mode)});
}

pub fn toggleTheme() void {
    mode = switch (mode) {
        .dark => .light,
        .light => .dark,
    };
    Vapor.lib.store("theme", @tagName(mode));
    Vapor.lib.toggleTheme();
}
